[tool.poetry]
name = "modapp"
version = "0.1.17"
description = ""
authors = ["Vladyslav Hnatiuk <vhnatiuk@ukr.net>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
loguru = "^0.6.0"
uvloop = { version = "^0.16.0", markers = "sys_platform != 'win32'" }
orjson = "^3.7.9"
pydantic = "^1.9.1"
googleapis-common-protos = "^1.56.4"


[tool.poetry.group.grpc.dependencies]
grpclib = "^0.4.2"


[tool.poetry.group.socketio.dependencies]
aiohttp = "^3.8.1"
python-socketio = "^5.7.1"

[build-system]
requires = ["poetry-core>=1.1.0b2"]
build-backend = "poetry.core.masonry.api"
