[tool.poetry]
name = "modapp"
version = "0.1.6"
description = ""
authors = ["Vladyslav Hnatiuk <vhnatiuk@ukr.net>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
loguru = "^0.6.0"
watchfiles = "^0.12"
uvloop = { version = "^0.16.0", markers = "sys_platform != 'win32'" }
command-runner = "^1.3.0"
orjson = "^3.6.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
